### ISSUE TITLE
Neos 5.0 compatible release

### ISSUE THREAD

**Issue by Nikdro** [flownative/neos-anchorlinks#10]
I just saw that the master branch already supports the new Neos version 5.0. Unfortunately there is no release yet that is compatible with Neos 5. So dev-master has to be used here.

Could you please provide a new version for Neos 5? Thanks a lot!

**Comment by breadlesscode** [comment]
Any news here? :)

**Comment by breadlesscode** [comment]
Tested with Neos 5.0 and Neos UI 5.0 and it works great :+1: 

Please press the release button 😄

**Comment by kdambekalns** [comment]
Huh, done with 1.1.3
