### ISSUE TITLE
I can't paste the link in shortcut target link or in text editor

### ISSUE THREAD

**Issue by sruegg** [flownative/neos-anchorlinks#4]
Hello,

Thanks for your package. Did help us a lot!

I've got a small (but annoying 😉) problem:

- I can't paste the copied link either in shortcut target link or in text editor: I can paste in the search box, but it says "nothing is found" and don't save the value (even when hitting [ENTER] a few times and/or clicking elsewhere).

I'm not sure the problem comes from this package or from a global config of the ckeditor.
Did you experience any problem with your package and the new Neos UI?

All packages at the latest versions.

Thanks.
Sébastien

**Comment by dimaip** [comment]
Hello, Sébastien!
Thanks for reporting! I can confirm the issue, and yes, the is the problem of the new UI, it doesn't automatically parse the links of type `node://` there. Could you please create an issue there?
